USE PETexam

CREATE TABLE Persons 
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Age INT NOT NULL,
	DateOfBirth DATE NOT NULL,
	Nationality NVARCHAR(100) NOT NULL,
	PersonalAddress NVARCHAR(100) NOT NULL,
	HeadShot NVARCHAR(MAX) NOT NULL, /* THIS IS A NVARCHAR BECAUSE I DON'T HAVE TIME TO LEARN PICTURE SAVINGS SO CALL IN PROGRAM AND DISPLAY FROM FOLDER */
	Remarks NVARCHAR(MAX)
	--GangID INT FOREIGN KEY REFERENCES Gangs(ID),
	--AgentID INT FOREIGN KEY REFERENCES Agents(ID)

);

CREATE TABLE Agents 
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Department NVARCHAR(100) NOT NULL,
	DateOfEmployment DATE NOT NULL,
	Salery FLOAT NOT NULL
);

CREATE TABLE Informants
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	--GangID INT NOT NULL FOREIGN KEY REFERENCES Gangs(ID),
	--AgentID INT NOT NULL FOREIGN KEY REFERENCES Agents(ID),
	Deployment DATETIME NOT NULL,
	EndOfDeployment DATETIME NOT NULL
);

CREATE TABLE Gangs
(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	GangName NVARCHAR(MAX) NOT NULL,
	LogoOrSymbol NVARCHAR(MAX) NOT NULL,  /* THIS IS A NVARCHAR BECAUSE I DON'T HAVE TIME TO LEARN PICTURE SAVINGS SO CALL IN PROGRAM AND DISPLAY FROM FOLDER */
	ThreatLevel NVARCHAR(100) NOT NULL,
	KnownLocations NVARCHAR(MAX), /* SHOULD BE ANOTHER TABLE OR A LIST OF LOCATIONS */
	HasActiveCases BIT NOT NULL
);

