//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThePetExamn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gangs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gangs()
        {
            this.Informants = new HashSet<Informants>();
            this.Persons = new HashSet<Persons>();
        }
    
        public int ID { get; set; }
        public string GangName { get; set; }
        public string LogoOrSymbol { get; set; }
        public string ThreatLevel { get; set; }
        public string KnownLocations { get; set; }
        public bool HasActiveCases { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Informants> Informants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Persons> Persons { get; set; }
    }
}
